package com.android.internal.util.framework;

import org.lsposed.lsparanoid.Obfuscate;

@Obfuscate
public final class Keybox {
    public static final class EC {
        public static final String PRIVATE_KEY = """
           -----BEGIN EC PARAMETERS-----
           BggqhkjOPQMBBw==
           -----END EC PARAMETERS-----
                """;
        public static final String CERTIFICATE_1 = """
           -----BEGIN EC PRIVATE KEY-----
            MHcCAQEEIJOtdY1T+ZgDWvad48cw6Ey4j9k93PKJexFKr+XRRBOCoAoGCCqGSM49
            AwEHoUQDQgAEeU14ILd16fsmbtAHT5Ay9Hs0Zb4wHKx+M0s55HaCSfiUpy07nj+S
            hfXux5HRth1Sv83NvGKMIVuf8y2SKqlcbQ==
           -----END EC PRIVATE KEY-----
                """;
        public static final String CERTIFICATE_2 = """
           -----BEGIN CERTIFICATE REQUEST-----
            MIIBeTCCAR8CAQAwgYoxCzAJBgNVBAYTAkNOMQ4wDAYDVQQIDAVIZW5hbjEPMA0G
            A1UEBwwGQW55YW5nMRMwEQYDVQQKDApDaHVuIEd1YW5nMRMwEQYDVQQLDApDaHVu
            IEd1YW5nMQ8wDQYDVQQDDAZtaS5jb20xHzAdBgkqhkiG9w0BCQEWEDk5NjE5MTQ0
            MUBxcS5jb20wWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAR5TXggt3Xp+yZu0AdP
            kDL0ezRlvjAcrH4zSznkdoJJ+JSnLTueP5KF9e7HkdG2HVK/zc28YowhW5/zLZIq
            qVxtoDIwFQYJKoZIhvcNAQkHMQgMBjEyMzQ1NjAZBgkqhkiG9w0BCQIxDAwKQ2h1
            biBHdWFuZzAKBggqhkjOPQQDAgNIADBFAiEA8LJpQnwUGnFCtu0ZL38xcmHA4Kmh
            3e9Yq0pWf4w0iMECIChDm/1g3GnYXZNs7djt6Oi9jAQ0Zlu3glQbUUtDkvsF
            -----END CERTIFICATE REQUEST-----
                """;
        public static final String CERTIFICATE_3 = """
                -----BEGIN EC PARAMETERS-----
BggqhkjOPQMBBw==
-----END EC PARAMETERS-----
                """;

    }

    public static final class RSA {
        public static final String PRIVATE_KEY = """
              -----BEGIN EC PRIVATE KEY-----
MHcCAQEEIJAqCmHeg1QievBEMDtSwJpyAee1qMQLC8XkAn49p1sFoAoGCCqGSM49
AwEHoUQDQgAEw/y94ahqXwuRgrO7zciYDgizikmmgjcEzymPIT5TMI0gxIOk9yZ9
x9FJN2OqSM74U89h7m7jPvkWXrOzqrHLuw==
-----END EC PRIVATE KEY-----
                """;
        public static final String CERTIFICATE_1 = """
                -----BEGIN CERTIFICATE REQUEST-----
MIIBgDCCAScCAQAwgZIxCzAJBgNVBAYTAkNOMQ4wDAYDVQQIDAVIZW5hbjEPMA0G
A1UEBwwGQW55YW5nMRMwEQYDVQQKDApDaHVuIEd1YW5nMRMwEQYDVQQLDApDaHVu
IEd1YW5nMRcwFQYDVQQDDA53d3cudmlpaWlzLmNvbTEfMB0GCSqGSIb3DQEJARYQ
OTk2MTkxNDQxQHFxLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABMP8veGo
al8LkYKzu83ImA4Is4pJpoI3BM8pjyE+UzCNIMSDpPcmfcfRSTdjqkjO+FPPYe5u
4z75Fl6zs6qxy7ugMjAVBgkqhkiG9w0BCQcxCAwGMTIzNDU2MBkGCSqGSIb3DQEJ
AjEMDApDaHVuIEd1YW5nMAoGCCqGSM49BAMCA0cAMEQCIH06sCF6+vNgBvcDmO4b
OwfLT3vxpFSgwOEtbEZctfmDAiBWM+Y4gNAfYw3iuKaUE9Stna1TG7lqtmRhNSXx
XVPPWw==
-----END CERTIFICATE REQUEST-----
                """;
        public static final String CERTIFICATE_2 = """
                -----BEGIN CERTIFICATE-----
MIICSTCCAe6gAwIBAgITKQGVhF7eb4QXEq191xP06HFiODAKBggqhkjOPQQDAjCB
kjELMAkGA1UEBhMCQ04xDjAMBgNVBAgMBUhlbmFuMQ8wDQYDVQQHDAZBbnlhbmcx
EzARBgNVBAoMCkNodW4gR3VhbmcxEzARBgNVBAsMCkNodW4gR3VhbmcxFzAVBgNV
BAMMDnd3dy52aWlpaXMuY29tMR8wHQYJKoZIhvcNAQkBFhA5OTYxOTE0NDFAcXEu
Y29tMB4XDTI0MDYwNDExMTc1NVoXDTI1MDYwNDExMTc1NVowgZIxCzAJBgNVBAYT
AkNOMQ4wDAYDVQQIDAVIZW5hbjEPMA0GA1UEBwwGQW55YW5nMRMwEQYDVQQKDApD
aHVuIEd1YW5nMRMwEQYDVQQLDApDaHVuIEd1YW5nMRcwFQYDVQQDDA53d3cudmlp
aWlzLmNvbTEfMB0GCSqGSIb3DQEJARYQOTk2MTkxNDQxQHFxLmNvbTBZMBMGByqG
SM49AgEGCCqGSM49AwEHA0IABMP8veGoal8LkYKzu83ImA4Is4pJpoI3BM8pjyE+
UzCNIMSDpPcmfcfRSTdjqkjO+FPPYe5u4z75Fl6zs6qxy7ujITAfMB0GA1UdDgQW
BBR0nMhX+QceAUK6pRIJ3bdDinUo8jAKBggqhkjOPQQDAgNJADBGAiEAomNh37Uz
J+rknFTm8Cc0DQo8uB2BHD8MZ8MZXfy3VJICIQCNVH7VpAJyhBnlFfVARfhNZhSY
r2hTMoU0qqEzhOeOIA==
-----END CERTIFICATE-----
                """;
                
        public static final String CERTIFICATE_3 = """
            -----BEGIN CERTIFICATE-----
MIICYjCCAgigAwIBAgIUEpviGr1GXTKedZWg71dZtRN0CoIwCgYIKoZIzj0EAwIw
gZIxCzAJBgNVBAYTAkNOMQ4wDAYDVQQIDAVIZW5hbjEPMA0GA1UEBwwGQW55YW5n
MRMwEQYDVQQKDApDaHVuIEd1YW5nMRMwEQYDVQQLDApDaHVuIEd1YW5nMRcwFQYD
VQQDDA53d3cudmlpaWlzLmNvbTEfMB0GCSqGSIb3DQEJARYQOTk2MTkxNDQxQHFx
LmNvbTAeFw0yNDA2MDQxMTI0MTlaFw0yNTA2MDQxMTI0MTlaMIGKMQswCQYDVQQG
EwJDTjEOMAwGA1UECAwFSGVuYW4xDzANBgNVBAcMBkFueWFuZzETMBEGA1UECgwK
Q2h1biBHdWFuZzETMBEGA1UECwwKQ2h1biBHdWFuZzEPMA0GA1UEAwwGbWkuY29t
MR8wHQYJKoZIhvcNAQkBFhA5OTYxOTE0NDFAcXEuY29tMFkwEwYHKoZIzj0CAQYI
KoZIzj0DAQcDQgAEeU14ILd16fsmbtAHT5Ay9Hs0Zb4wHKx+M0s55HaCSfiUpy07
nj+ShfXux5HRth1Sv83NvGKMIVuf8y2SKqlcbaNCMEAwHQYDVR0OBBYEFPhK7uMs
cN0vo0TyqmraT+DQLoqnMB8GA1UdIwQYMBaAFHScyFf5Bx4BQrqlEgndt0OKdSjy
MAoGCCqGSM49BAMCA0gAMEUCIBQDxiUC8A7aKNmtBZmovEC2HS6m9EBsoWza/Phl
USuEAiEA7WAwZfUbngRNaigewd2YmYbmRixuXWfHoAe8XBpJ7vY=
-----END CERTIFICATE-----
            """;
    }
}
